<div class="content">
    
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h5 class="card-category">All Invoices List</h5>
                <h4 class="card-title"> Invoices </h4>
                <?php
                     echo $this->tag->linkTo([
                        "invoice/add/",
                        "Add New",
                        "class" => "btn btn-primary",
                        "title" => "Edit Article"
                    ]); 
                ?>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table">
                    <thead class=" text-primary">
                      <th>
                        Customer Name
                      </th>
                      <th>
                        Product Name
                      </th>
                      <th>
                        Amount Due
                      </th>
                      <th>
                        Amount Paid
                      </th>
                      <th>
                        Description
                      </th>
                      <th class="text-right">
                        Date Created
                      </th>
                    </thead>
                    <tbody>
                        
                    <?php   
                            
                        foreach($this->view->invoices as $key => $invoice){ ?>
                            <tr>
                                <td>                                   
                                    <?= $invoice['customer_name'] ?>
                                </td>
                                <td>                                   
                                    <?= $invoice['product_name'] ?>
                                </td>                                
                                <td >
                                    R<?= number_format($invoice['amount_due'],2) ?>
                                </td>
                                <td >
                                    <?= is_numeric($invoice['amount_paid']) ?  "R".number_format($invoice['amount_paid'],2) : $invoice['amount_paid'] ?>
                                </td>
                                <td >
                                    <?= $invoice['description'] ?>
                                </td>
                                <td class="text-right">
                                    <?= $invoice['date_created'] ?>
                                </td>                        
                            </tr>
                        <?php } ?>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>