<div class="content">
    
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h5 class="card-category">All Persons List</h5>
                <h4 class="card-title"> Customers </h4>
                <?php
                     echo $this->tag->linkTo([
                        "customer/add/",
                        "Add New",
                        "class" => "btn btn-primary",
                        "title" => "Edit Article"
                    ]); 
                ?>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table">
                    <thead class=" text-primary">
                      <th>
                        Name
                      </th>
                      <th>
                        Address
                      </th>
                      <th>
                        Balance
                      </th>
                      <th class="text-right">
                        Date Created
                      </th>
                      <th class="text-center">
                        Action
                      </th>
                    </thead>
                    <tbody>
                        
                    <?php   
                                    
                        foreach($this->view->customers as $key => $customer){ ?>
                            <tr>
                                <td>                                   
                                    <?= $customer['name'] ?>
                                </td>
                                <td>
                                    <?= $customer['address'] ?>
                                </td>
                                <td >
                                    <?= $customer['balance'] ?>
                                </td>
                                <td class="text-right">
                                    <?= $customer['date_created'] ?>
                                </td>
                                <td class="text-center">
                                    <a href="#" data-customer-id = "<?=$customer['id']?>" class = "delete-customer">Delete</a>  &nbsp; &nbsp;
                                    <?php 
                                        echo $this->tag->linkTo([
                                            "customer/edit/".$customer['id'],
                                            "Edit",
                                        ]); 
                                    ?>
                                </td>                        
                            </tr>
                        <?php } ?>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>