<div class="content">
    <div class="row">
        <div class="col-md-8">
        <div class="card">
            <div class="card-header"> 
            <h5 class="title">Pay Invoice</h5>
            </div>
            <div class="card-body">
            <?= $this->tag->form("customer/addSubmit"); ?>
                <div class="row">
                <div class="col-md-6 pr-1">
                    <div class="form-group">
                        <label>Product: <br/>
                            <strong>
                                <?= $this->view->invoice_details[0]['product_name'] ?> 
                            </strong>
                        </label>
                </div>
                <div class="col-md-6 pl-1">
                    <div class="form-group">
                        <label>Amount Due: 
                            <strong><?= $this->view->invoice_details[0]['amount_due'] ?></strong>
                        </label>
                    </div>
                </div>
                <div class="col-md-6 pl-1">
                    <div class="form-group">
                        <label>Payment Amount:</label>
                        <input type ="number" class = "form-control"/>                        
                    </div>
                </div>
                </div>
                <div class="col-12 d-flex justify-content-end">                      
                    <div class="col-6">                    
                        <?= $form->render('update'); ?> 
                    </div>                                        
                </div>                 
            </form>
            </div>
        </div>
        </div>
    </div>
</div>