<div class="content">
    <div class="row">
        <div class="col-md-8">
        <div class="card">
            <div class="card-header"> 
            <h5 class="title">Edit Customer</h5>
            </div>
            <div class="card-body">
                <?php
                    $customer_id = $this->view->customer[0]['id'];
                ?>
            <?= $this->tag->form("customer/editSubmit/$customer_id"); ?>
                <div class="row">
                <div class="col-md-6 pr-1">
                    <div class="form-group">
                    <label>First Name</label>
                         <?= $form->render('name'); ?>
                    </div>
                </div>
                <div class="col-md-6 pl-1">
                    <div class="form-group">
                    <label>Last Name</label>
                        <?= $form->render('last_name'); ?>
                    </div>
                </div>
                </div>
                <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                    <label>Address</label>
                        <?= $form->render('address'); ?>
                    </div>
                </div>
                </div>
                <div class="row">
                <div class="col-md-4 pr-1">
                    <div class="form-group">
                        <label>Balance</label>
                        <?= $form->render('balance'); ?>                   
                    </div>
                </div>
                <div class="col-md-4 px-1">
                    <div class="form-group">
                    <label>Username</label>
                        <?= $form->render('username'); ?>     
                    </div>
                </div>
                <div class="col-md-4 pl-1">
                    <div class="form-group">
                    <label>Password</label>
                        <?= $form->render('password'); ?>      
                    </div>
                </div>
                </div>
                <div class="col-12 d-flex justify-content-end">                      
                    <div class="col-6">                    
                        <?= $form->render('update'); ?> 
                    </div>                                        
                </div>                 
            </form>
            </div>
        </div>
        </div>
    </div>
</div>